var={'a':{'b':[44,66,99,{'c':(False,True,'Hello'),'h':'Good Bye'},'SQL'],'p':(420,840)}}

print(len(var))

#positive indexing
print(var['a']['b'][0])
print(var['a']['b'][1])
print(var['a']['b'][2])
print(var['a']['b'][3]['c'][0])
print(var['a']['b'][3]['c'][1])
print(var['a']['b'][3]['c'][2])
print(var['a']['b'][3]['c'][2][0])
print(var['a']['b'][3]['c'][2][1])
print(var['a']['b'][3]['c'][2][2])
print(var['a']['b'][3]['c'][2][3])
print(var['a']['b'][3]['c'][2][4])
print(var['a']['b'][3]['h'])
print(var['a']['b'][3]['h'][0])
print(var['a']['b'][3]['h'][1])
print(var['a']['b'][3]['h'][2])
print(var['a']['b'][3]['h'][3])
print(var['a']['b'][3]['h'][5])
print(var['a']['b'][3]['h'][6])
print(var['a']['b'][3]['h'][7])
print(var['a']['b'][4][0])
print(var['a']['b'][4][1])
print(var['a']['b'][4][2])
print(var['a']['p'])
print(var['a']['p'][0])
print(var['a']['p'][1])

#Negative indexing
print(var['a']['p'])
print(var['a']['p'][-1])
print(var['a']['p'][-2])
print(var['a']['b'])
print(var['a']['b'][-1])
print(var['a']['b'][-2])
print(var['a']['b'][-2]['c'][-1])
print(var['a']['b'][-2]['c'][-1][-1])
print(var['a']['b'][-2]['c'][-1][-2])
print(var['a']['b'][-2]['c'][-1][-3])
print(var['a']['b'][-2]['c'][-1][-4])
print(var['a']['b'][-2]['c'][-1][-5])
print(var['a']['b'][-2]['c'][-2])
print(var['a']['b'][-2]['c'][-3])
print(var['a']['b'][-2]['h'])
print(var['a']['b'][-2]['h'][-8])
print(var['a']['b'][-2]['h'][-7])
print(var['a']['b'][-2]['h'][-6])
print(var['a']['b'][-2]['h'][-5])
print(var['a']['b'][-2]['h'][-3])
print(var['a']['b'][-2]['h'][-2])
print(var['a']['b'][-2]['h'][-1])
print(var['a']['b'][-3])
print(var['a']['b'][-4])
print(var['a']['b'][-5])
